services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - type: bind
        source: ./mosquitto/config
        target: /mosquitto/config
      - type: bind
        source: ./mosquitto/log
        target: /mosquitto/log
      - type: bind
        source: ./mosquitto/data
        target: /mosquitto/data
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
  nestjs:
    env_file:
      - .env
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      NODE_ENV: "production"
      PORT: "3000"
      MOSQUITTO_HOST: "mosquitto"
      MOSQUITTO_PORT: "1883"
